functionDir <- "./R/"
functionList <- list.files(path = functionDir)
for(i in functionList){
  source(paste0(functionDir,i))
}

<!-- source("./R/PrincipalComponentCalculation.R") -->
<!-- source("./R/ExplainedVarainceCalculation.R") -->
<!-- results <- pcresults(data = allData) -->
<!-- explainedvarianceratio <- explained_variance_ratio(results) -->
<!-- pcsum <- pcsummary(results) -->
<!-- threshold <- threshold(cutoff, pcsum) -->
<!-- screecumulativethresholdplot <- screecumulativethreshold(pcsum, threshold) -->
<!-- pcdf <- pcdf(results) -->
<!--  <- plotinput() -->
<!-- pcagridlegend <- pcagridlegend(pcdf, colour, SH, AL, SZ) -->
<!-- my_fn1 <- my_fn1(pcdf) -->
<!-- g<- pcagrid(threshold, explainedvarianceratio, pcdf, my_fn1) -->
<!-- gpairs_lower(g) -->

#load data to test functions
```{r}
ann<-local(get(load("~/OneDrive - Murdoch University/datasets/covid19/bioGune/dataElements/covid19_bioGune_PLA_ANN.daE")))
aaMeta1<-ann@obsDescr[[1]]

aa<-local(get(load(file.path("~/OneDrive - Murdoch University/datasets/covid19/bioGune/dataElements/covid19_bioGune_PLA_SPC.daE"))))
aaData<-data.frame(apply(aa@.Data,2,as.numeric)) #lipoproteins
aaMeta2<-aa@obsDescr[[1]] #metadata from covid19_mauritius_PLA_LIPO.daE file

# match Amino Acids and both Annotations
aaMeta1<-aaMeta1[which(aaMeta1$sampleID %in% aaMeta2$sampleID),]
aaData<-aaData[which(aaMeta2$sampleID %in% aaMeta1$sampleID),]
aaMeta2<-aaMeta2[which(aaMeta2$sampleID %in% aaMeta1$sampleID),]

aaMetaF<-merge(aaMeta1,
                  aaMeta2,
                  by.x ="sampleID",by.y = "sampleID")
rm(aaMeta1, aaMeta2, aa, ann)

BIOspcglyc<-cbind(aaData, aaMetaF)
rm(aaData, aaMetaF)

which(BIOspcglyc[, 1:8]=="Inf")
which(is.na(BIOspcglyc[, 1:8]))
which(is.na(BIOspcglyc$age))
unique(BIOspcglyc$sex)

unique(BIOspcglyc$group)
BIOspcglyc$covid_status<-ifelse(BIOspcglyc$group =="COVID-pos","covid", ifelse(BIOspcglyc$group=="preCOVID","control", "control"))
```

#tests
```{r}
loadPackages(myPackages = c("ggplot2",
                            "ggplotly",
                            "plotly",
                            "prcomp", 
                            "tidyverse", 
                            "ggpubr",
                            "GGally",
                            "cowplot",
                            "gridExtra",
                            "rlist"))

a<- pcResults(BIOspcglyc[,1:8], annotation = BIOspcglyc[,-1:-8])
b <- screeCumulativeThreshold(pcResultsObject = a)
#b<- plotInput(screeCumulativeThresholdObject = output, CO = "covid_status", SH = "sex", SZ = 5, AL = 0.4)

#gridplot tests
##working
pcaGrid(screeCumulativeThresholdObject = b, CO = "covid_status", COtitle = "covid")
pcaGrid(screeCumulativeThresholdObject = b, CO = 1, COtitle = "covid")
pcaGrid(screeCumulativeThresholdObject = b, CO = "covid_status", SZ = "age", AL = "bmi", COtitle = "covid", SZtitle = "Age")


pcaGrid(screeCumulativeThresholdObject = b, CO = "covid_status", SZ = 0.5, COtitle = "covid", SZtitle = "Age")


pcaGrid(screeCumulativeThresholdObject = b, CO = "covid_status", SH = "sex", SZ = 1, AL = 1, COtitle = "covid")
pcagrid(screeCumulativeThresholdObject = b, CO = "covid_status", SH = NULL, SZ = "age", AL = 1, COtitle = "covid")
pcagrid(screeCumulativeThresholdObject = b, CO = "covid_status", SH = NULL, SZ = 5, AL = "age", COtitle = "covid")
pcagrid(screeCumulativeThresholdObject = b, CO = "covid_status", SH = "sex", SZ = "age", AL = 1, COtitle = "covid")
pcagrid(screeCumulativeThresholdObject = b, CO = "covid_status", SH = "sex", SZ = 5, AL = "age", COtitle = "covid")
pcagrid(screeCumulativeThresholdObject = b, CO = "covid_status", SH = "sex", SZ = "age", AL = "bmi", COtitle = "covid")
pcagrid(screeCumulativeThresholdObject = b, CO = "covid_status", SH = NULL, SZ = "age", AL = "bmi", COtitle = "covid")
pcagrid(screeCumulativeThresholdObject = b, CO = "covid_status", SH = NULL, SZ = 5, AL = 1, COtitle = "covid")
```
#legend back up don't touch
```{r}
pcagridlegend<-function(screecumulativethresholdobject, x = "PC1", y = "PC2", CO, SH, AL, SZ, COtitle, SHtitle, SZtitle, ALtitle){
  
  output <- plotinput(screecumulativethresholdobject, CO, SH, SZ, AL)
  # Get required data for plotting
  
  gu <- if(class(SH) == "character" & class(SZ) == "numeric" & class(AL) == "numeric") {
    guides(alpha = "none", size = "none")
  } else if (class(SH) == "NULL" & class(SZ) == "character" & class(AL) == "numeric") {
    guides(alpha = "none", shape = "none")
  } else if (class(SH) == "NULL" & class(SZ) == "numeric" & class(AL) == "character") {
    guides(shape = "none", size = "none")
  } else if (class(SH) == "character" & class(SZ) == "character" & class(AL) == "numeric") {
    guides(alpha = "none" )
  } else if (class(SH) == "character" & class(SZ) == "numeric" & class(AL) == "character") {
    guides(size = "none")
  } else if (class(SH) == "NULL" & class(SZ) == "character" & class(AL) == "character") {
    guides(shape = "none")
  } else if (class(SH) == "character" & class(SZ) == "character" & class(AL) == "character") {
    guides()
  } else if (class(SH) == "NULL" & class(SZ) == "numeric" & class(AL) == "numeric") {
    guides(shape = "none", size = "none", alpha = "none")
  }
  
  test <- ggplot(data = output$data$pcdf, aes(x = .data[[x]], y = .data[[y]], color = output$CO, shape = output$SH, alpha = output$AL, size = output$SZ)) +
    geom_point() +
    gu +
    labs(color = COtitle, shape = SHtitle, size = SZtitle, alpha = ALtitle ) +
    theme_minimal()
  return(test)
}

test <- pcagridlegend(screecumulativethresholdobject = output, x = "PC1", y = "PC2", CO = "covid_status", SH="sex", AL="age", SZ=0.1, COtitle = "COV", SHtitle= "gender", SZtitle=NULL, ALtitle="Age")
```

#working my_fn1, don't touch 
```{r}
  my_fn1 <- function(data, mapping, method="stat_ellipse"){
    p <- ggplot(data = data, mapping = mapping) +
    #  geom_point() +
    # geom_point(aes(color = .data[[colour]], shape = output$SH, size=output$SZ, alpha=output$AL)) +
    # stat_ellipse(aes(group=interaction(.data[[colour]], color=.data[[colour]]), color=.data[[colour]]))+
    theme_minimal()+
    geom_hline(yintercept=0, linetype="dashed", color = "black")+
    geom_vline(xintercept=0, linetype="dashed", colour= "black")
  return(p)
}

pcagrid <-function(screecumulativethresholdobject, CO, SH, SZ, AL){

  output <- plotinput(screecumulativethresholdobject, CO, SH, SZ, AL)
  thresh <- output$data$treshold
  #   my_fn1 <- function(data, mapping, method="stat_ellipse"){
  #   p <- ggplot(data = output$data$pcdf, mapping=mapping) +
  #     geom_point(aes(color = .data[[colour]], shape = output$SH, size=output$SZ, alpha=output$AL)) +
  #     stat_ellipse(aes(group=interaction(.data[[colour]], color=.data[[colour]]), color=.data[[colour]]))+
  #     theme_minimal()+
  #     geom_hline(yintercept=0, linetype="dashed", color = "black")+
  #     geom_vline(xintercept=0, linetype="dashed", colour= "black")
  #   p
  # }

  title <- list()
  for (i in 1:thresh) {
    title[[i]] <- paste0('PC', i, ' (', round(output$data$explained_variance_ratio[i], 1), '%)')
  }
  title<-unlist(title)

  pcagridplot<-GGally::ggpairs(data = output$data$pcdf[,1:thresh],
                               columnLabels = c(title),
                               diag="blank",
                               upper="blank",
                               #upper=list(continuous = my_fn1),
                               lower=list(continuous = my_fn1),
                               #legend = grab_legend(test),
                               progress = F,
                               switch = "both") +
    geom_point(aes(colour = output$CO, shape = output$SH, size=output$SZ, alpha=output$AL)) +
    stat_ellipse(aes(group=interaction(output$CO, color=output$CO), color=output$CO))+
    theme_bw() +
    theme(strip.background = element_rect(fill = "white"),
          axis.text.x = (element_text(size=rel(0.7), angle=0)),
          axis.text.y = (element_text(size=rel(0.7), angle=0)),
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          panel.border = element_rect(fill = NA,colour = "grey35"))
  pcagridplot

}
```
#working pcagrid, don't touch 
```{r}
pcagrid <-function(pcresultobject, colour, SH, SZ, AL){

  output <- pcresultobject
  #t <- 4
  thresh <- 4
    #as.numeric(output$data$treshold)

  # Get required data for plotting

  #shape
  SH <- if(class(SH) == "NULL") {
    SH = SH
  }else if(class(SH) == "character"){
    SH = output$pcdf[,SH]
  }
  #SH = output$pcdf$SH

  #size
  SZ <- if(class(SZ) == "numeric") {
    SZ = SZ
  }else if (class(SZ) == "character"){
    SZ = output$pcdf[,SZ]
  }
  #SZ = output$pcdf$SZ

  #alpha
  AL <- if(class(AL) == "numeric") {
    AL = AL
  }else if (class(AL) == "character"){
    AL = output$pcdf[,AL]
  }
  #AL = output$pcdf$AL


my_fn1 <- function(data, mapping, method="stat_ellipse"){
  p <- ggplot(data = df, mapping=mapping) + 
    geom_point(aes(color = .data[[colour]], shape = SH, size=SZ, alpha=AL)) + 
    stat_ellipse(aes(group=interaction(.data[[colour]], color=.data[[colour]]), color=.data[[colour]]))+
  theme_minimal()+
  geom_hline(yintercept=0, linetype="dashed", color = "black")+
  geom_vline(xintercept=0, linetype="dashed", colour= "black")
  p
} 

  # myfun <- ggplot(data = output$pcdf) +
  # #myfun <- ggplot(data = output$pcdf, mapping = mapping) +
  #   geom_point(aes(color = .data[[colour]], shape = SH, size = SZ, alpha = AL)) +
  #   stat_ellipse(aes(group = interaction(.data[[colour]], color = .data[[colour]]), color = .data[[colour]]))+
  #   theme_minimal()+
  #   geom_hline(yintercept = 0, linetype = "dashed", color = "black")+
  #   geom_vline(xintercept = 0, linetype = "dashed", color = "black")

  title <- list()
  for (i in 1:thresh) {
    title[[i]] <- paste0('PC', i, ' (', round(output$explained_variance_ratio[i], 1), '%)')
  }
  title<-unlist(title)

  pcagridplot<-GGally::ggpairs(output$pcdf[,1:thresh],
                         columnLabels = c(title),
                         diag="blank",
                         upper="blank",
                         #upper=list(continuous = my_fn1),
                         lower=list(continuous = my_fn1),
                         #legend = grab_legend(test),
                         progress = F,
                         switch = "both") +
                         theme_bw() +
                         theme(strip.background = element_rect(fill = "white"),
                                axis.text.x = (element_text(size=rel(0.7), angle=0)),
                                axis.text.y = (element_text(size=rel(0.7), angle=0)),
                                panel.grid.major = element_blank(),
                                panel.grid.minor = element_blank(),
                                panel.border = element_rect(fill = NA,colour = "grey35"))
  pcagridplot

}

pcagrid(pcresultobject = a, colour="covid_status", SH=NULL, SZ=1, AL=0.4)


# explained_variance_ratio(results = a)
# b<- pcsummary(results = a)
# t<- threshold(pcsum = b)
# screecumulativethreshold(pcsum = b, threshold = t)
# p<-pcdf(results = a, annotation = BIOspcglyc[,-1:-8])
# 
# 
# inputData <- plotinput(data = aaMeta1, SZ = aaMeta1$sex, SH = aaMeta1$age, AL = 0.4)
# 
# append(myList, item, after = index)
```

